spring:
  application:
    name: webshop
  profiles:
    active: default
  servlet:
    multipart:
      max-file-size: 1048576 # 1MB

webshop:
  jwt:
    secret: ${JWT_SECRET_KEY}
    accessTokenExpiration: 300 # 5m
    refreshTokenExpiration: 604800 # 7d

  file-extensions-config:
    allowed-file-extensions: jpg,jpeg,png,bmp

  product-photos-upload-directory-config:
    path: ${PRODUCT_PHOTOS_UPLOAD_DIRECTORY_PATH}

  profile-avatar-upload-directory-config:
    path: ${PROFILE_AVATAR_UPLOAD_DIRECTORY_PATH}
